name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.0

  provider: ^6.1.1
  http: ^1.2.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/localization/